[workspace]
resolver = "2"
members = ["crates/voicegarden-spd"]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/AACTools/VoiceGarden-SPD"
authors = ["will wade <willwade@gmail.com>"]

[profile.release]
lto = true
codegen-units = 1
strip = true
